version: '3.5'
services:

  # Image--infrastructure:mariadb
  # mariadb:
  #   image: mariadb:10.5.9
  #   hostname: mariadb
  #   container_name: mariadb
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: resumegeni
  #   networks:
  #     - nodelocal-private
  #   ports:
  #     - '23306:3306'
  #   volumes:
  #     - ./conf/init:/docker-entrypoint-initdb.d/:ro
  #     - type: bind
  #       source: ./conf/mariadb.cnf
  #       target: /etc/mysql/conf.d/docker.cnf
  #       read_only: true
  #     - type: volume
  #       source: mariadb
  #       target: /var/lib/mysql

  # # Image--infrastructure:redis
  # redis:
  #   image: redis:4.0.8-alpine
  #   networks:
  #     - nodelocal-private
  #   volumes:
  #     - type: volume
  #       source: redis
  #       target: /data

  # Image--app:resumegeni_app
  # resumegeni_app:
  #   build:
  #     context: ../app
  #     dockerfile: Dockerfile_app
  #   hostname: resumegeni_app
  #   restart: always
  #   ports:
  #     - '127.0.0.1:8880:3000'
  #   command: sh -c 'serve -s dist'
  #   volumes:
  #     - type: bind
  #       source: ../app
  #       target: /app
  #   networks:
  #     - nodelocal
  #     - nodelocal-private

  # Image--app:resumegeni_backend
  resumegeni_backend:
    build:
      context: ../backend
      dockerfile: Dockerfile_backend
    hostname: resumegeni_backend
    restart: always
    ports:
      - '127.0.0.1:9000:8000'
    command: sh -c 'sh docker_start_init_scripts.sh'
    volumes:
      - type: bind
        source: ../backend
        target: /var/www/html
      - type: bind
        source: ./conf/php.ini
        target: /etc/php7/php.ini
    networks:
      - nodelocal
      - nodelocal-private
    # depends_on:
    #   - mariadb

  # Image--infrastructure:pma
  # pma:
  #   image: phpmyadmin/phpmyadmin:4.7.9-1
  #   container_name: rbr-phpMyAdmin
  #   environment:
  #     PMA_HOST: mariadb
  #   networks:
  #     - nodelocal-private
  #   ports:
  #     - '2082:80'
  #   volumes:
  #     - type: bind
  #       source: ./conf/pma.config.user.inc.php
  #       target: /etc/phpmyadmin/config.user.inc.php
  #       read_only: true
  #   depends_on:
  #     - mariadb

  #   # Service--CoderCloudDevelopment
  # code-server:
  #   image: ghcr.io/linuxserver/code-server
  #   container_name: rbr-code-server
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/London
  #     - PASSWORD=password #optional
  #   volumes:
  #     - type: bind
  #       source: ../backend
  #       target: /config/workspace
  #     - ./conf/config:/config
  #   ports:
  #     - '2086:8443'
  #   restart: unless-stopped

#
# Data volume definitions
#
volumes:
  mariadb:
  redis:

#
# Network definitions
#
networks:
  nodelocal:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: 'true'
      com.docker.network.bridge.enable_ip_masquerade: 'true'
  nodelocal-private:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: 'true'
      com.docker.network.bridge.enable_ip_masquerade: 'false'
